// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

interface IWorldIdVerifier {
    /**
     * @notice Verifies the zero-knowledge proof generated by the World ID client.
     */
    function verifyProof(
        uint256 root,
        uint256 signalHash,
        uint256 nullifierHash,
        uint256[8] calldata proof
    ) external view;
}

contract ZkAirdropDistributor is ReentrancyGuard {
    IERC20 public immutable airdropToken;
    IWorldIdVerifier public immutable worldIdRouter;
    
    uint256 public immutable claimAmount;
    mapping(uint256 => bool) public registeredNullifiers;

    event AirdropClaimed(address indexed recipient, uint256 amount);

    constructor(
        address _airdropToken,
        address _worldIdRouter,
        uint256 _claimAmount
    ) {
        airdropToken = IERC20(_airdropToken);
        worldIdRouter = IWorldIdVerifier(_worldIdRouter);
        claimAmount = _claimAmount;
    }

    /**
     * @notice Processes a Sybil-resistant token claim via verified World ID ZK-proofs.
     * @param recipient The target destination wallet for the token transfer.
     * @param root The root commitment hash of the identity Merkle tree.
     * @param nullifierHash The unique fingerprint generated to prevent double-claiming.
     * @param proof The 8-element Snark proof array.
     */
    function claimTokens(
        address recipient,
        uint256 root,
        uint256 nullifierHash,
        uint256[8] calldata proof
    ) external nonReentrant {
        require(!registeredNullifiers[nullifierHash], "AirdropError: Identity has already claimed this distribution");

        // Bind the recipient's wallet address deterministically to the ZK-proof signal commitment
        uint256 signalHash = uint256(keccak256(abi.encodePacked(recipient)));

        // Execute external view call to validate proof soundness against World ID router
        worldIdRouter.verifyProof(
            root,
            signalHash,
            nullifierHash,
            proof
        );

        // Permanently record the nullifier to safeguard the distribution vault against reclaims
        registeredNullifiers[nullifierHash] = true;

        // Disburse token assets from contract reserves
        require(airdropToken.transfer(recipient, claimAmount), "AirdropError: Vault transfer failed");

        emit AirdropClaimed(recipient, claimAmount);
    }
}
